version: '3.9'

services:
  translator:
    container_name: translator
    image: translator:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - '80:80'
    environment:
      - APP_PORT=80
      - GOOGLE_CLOUD_PROJECT_ID=cloudcomputingii
      - GOOGLE_APPLICATION_CREDENTIALS=./service-account.json
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_APP_ID=translator
      - LOG_LEVEL=debug
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
